### PR TITLE
Only store one id per document

### PR DESCRIPTION
**Pull request by idris**
I changed this a bit so that instead of using the `session_id` field, it just stores the session id in the `id` field.

### CODE REVIEW

**Comment by ryanfitz** [comment]
The reason why you don't want to use the mongoid generated id which is BSON::ObjectId is that they are actually easy for a malicious user to guess and hijack other users cookies.

**Comment by idris** [comment]
My implementation doesn't use Mongo generated BSON::ObjectId's.  It uses Strings, and it uses the same session id's that were being stored in the session_id field.

Mongoid/Mongo allows you to use Strings as the key, and that's what I've done here, and I've manually assigned the id to be the session_id provided by rails.

**Comment by sanford** [comment]
If this patch does go through, can we modify the following?

change:
    @@session_class.find(id) rescue @@session_class.new(:id => id)

to:
    @@session_class.first(:conditions => {:id => id}) || @@session_class.new(:id => id)

exceptions are very slow in Ruby

**Comment by idris** [comment]
Okay.. How about `@@session_class.find_or_create_by(:id => id)`?

**Comment by sanford** [comment]
Even better.  Sure.

**Comment by idris** [comment]
K That's been committed here: idris/mongoid_session_store@f0f280215be3a6121a8e902fb2b9b252d7efc670

Now if we can just convince ryanfitz that this change is for the better :)

**Comment by idris** [comment]
Closing this request in favor of [the new one](http://github.com/ryanfitz/mongoid_session_store/pull/4)

**Pull request closed without merging**
